"""Add DPO fields to Feedback

Revision ID: 80b3daf30ef4
Revises: 883f65dea834
Create Date: 2026-07-03 14:07:45.189402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '80b3daf30ef4'
down_revision: Union[str, Sequence[str], None] = '883f65dea834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('latest_resume_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('datasetversion', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('modelversion', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('pipelineentry', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.alter_column('model_version_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('input_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_column('output_data')
        batch_op.drop_column('latency_ms')

    with op.batch_alter_table('recruiterfeedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'REJECTED', 'HIRED', name='feedbackaction'), nullable=False))
        batch_op.add_column(sa.Column('model_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dataset_version', sa.String(), nullable=True))
        batch_op.alter_column('candidate_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('is_helpful',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('recruiterfeedback', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('is_helpful',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('dataset_version')
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('prompt_type')
        batch_op.drop_column('model_version')
        batch_op.drop_column('action')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latency_ms', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('output_data', sqlite.JSON(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('input_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('model_version_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('pipelineentry', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('candidate_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('modelversion', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('datasetversion', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('latest_resume_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
