"""initial_migration

Revision ID: 883f65dea834
Revises: 
Create Date: 2026-07-01 01:52:40.247723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '883f65dea834'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('latest_resume_id', sa.UUID(), nullable=True),
    sa.Column('profile_jsonb', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['latest_resume_id'], ['resume.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_email'), 'candidate', ['email'], unique=True)
    op.create_index(op.f('ix_candidate_id'), 'candidate', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_name'), 'candidate', ['name'], unique=False)
    op.create_table('datasetversion',
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasetversion_id'), 'datasetversion', ['id'], unique=False)
    op.create_index(op.f('ix_datasetversion_version_tag'), 'datasetversion', ['version_tag'], unique=True)
    op.create_table('job',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED', name='jobstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    op.create_table('modelversion',
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelversion_id'), 'modelversion', ['id'], unique=False)
    op.create_index(op.f('ix_modelversion_version_tag'), 'modelversion', ['version_tag'], unique=True)
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', 'HIRING_MANAGER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('auditlog',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_entity_id'), 'auditlog', ['entity_id'], unique=False)
    op.create_index(op.f('ix_auditlog_entity_type'), 'auditlog', ['entity_type'], unique=False)
    op.create_index(op.f('ix_auditlog_id'), 'auditlog', ['id'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    op.create_table('pipelineentry',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('SOURCED', 'APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='pipelinestage'), nullable=False),
    sa.Column('ranking_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('matched_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelineentry_candidate_id'), 'pipelineentry', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_pipelineentry_id'), 'pipelineentry', ['id'], unique=False)
    op.create_index(op.f('ix_pipelineentry_job_id'), 'pipelineentry', ['job_id'], unique=False)
    op.create_index(op.f('ix_pipelineentry_ranking_score'), 'pipelineentry', ['ranking_score'], unique=False)
    op.create_index(op.f('ix_pipelineentry_stage'), 'pipelineentry', ['stage'], unique=False)
    op.create_table('prediction',
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['modelversion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_id'), 'prediction', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_model_version_id'), 'prediction', ['model_version_id'], unique=False)
    op.create_table('recruiterfeedback',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiterfeedback_candidate_id'), 'recruiterfeedback', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recruiterfeedback_id'), 'recruiterfeedback', ['id'], unique=False)
    op.create_index(op.f('ix_recruiterfeedback_job_id'), 'recruiterfeedback', ['job_id'], unique=False)
    op.create_index(op.f('ix_recruiterfeedback_user_id'), 'recruiterfeedback', ['user_id'], unique=False)
    op.create_table('resume',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_candidate_id'), 'resume', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resume_id'), 'resume', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_id'), table_name='resume')
    op.drop_index(op.f('ix_resume_candidate_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_recruiterfeedback_user_id'), table_name='recruiterfeedback')
    op.drop_index(op.f('ix_recruiterfeedback_job_id'), table_name='recruiterfeedback')
    op.drop_index(op.f('ix_recruiterfeedback_id'), table_name='recruiterfeedback')
    op.drop_index(op.f('ix_recruiterfeedback_candidate_id'), table_name='recruiterfeedback')
    op.drop_table('recruiterfeedback')
    op.drop_index(op.f('ix_prediction_model_version_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_pipelineentry_stage'), table_name='pipelineentry')
    op.drop_index(op.f('ix_pipelineentry_ranking_score'), table_name='pipelineentry')
    op.drop_index(op.f('ix_pipelineentry_job_id'), table_name='pipelineentry')
    op.drop_index(op.f('ix_pipelineentry_id'), table_name='pipelineentry')
    op.drop_index(op.f('ix_pipelineentry_candidate_id'), table_name='pipelineentry')
    op.drop_table('pipelineentry')
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_entity_type'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_entity_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_modelversion_version_tag'), table_name='modelversion')
    op.drop_index(op.f('ix_modelversion_id'), table_name='modelversion')
    op.drop_table('modelversion')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_datasetversion_version_tag'), table_name='datasetversion')
    op.drop_index(op.f('ix_datasetversion_id'), table_name='datasetversion')
    op.drop_table('datasetversion')
    op.drop_index(op.f('ix_candidate_name'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_id'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_email'), table_name='candidate')
    op.drop_table('candidate')
    # ### end Alembic commands ###
